/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QCommandLinkButton>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>
#include <QValidator>
#include "alinum.h"
#include "forgetpass.h"
#include "logincircling.h"
#include "network.h"
#include "newuser.h"
#include "refreshcircle.h"
#include "titlebar1.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QCheckBox *autologin;
    QPushButton *newuser;
    QTabWidget *tabWidget;
    QWidget *Codelogin;
    QFrame *line_8;
    QFrame *line_4;
    QLabel *label;
    QLabel *label_2;
    QPushButton *alinum_2;
    RefreshCicle *widget;
    QWidget *Passlogin;
    QLabel *logo;
    QLineEdit *ddnum;
    QFrame *line_2;
    QFrame *line_5;
    QLineEdit *ddpass;
    QCommandLinkButton *login;
    QFrame *line_6;
    QPushButton *forgetpass;
    QFrame *line;
    QFrame *line_3;
    QFrame *line_7;
    QPushButton *areanum;
    QPushButton *alinum;
    Forgetpass *ForgetPass;
    Newuser *NewUser;
    Alinum *AliNum;
    QPushButton *back;
    QLabel *label_4;
    QLabel *label_3;
    titlebar1 *titlebar;
    QPushButton *setNetwork;
    QLabel *label_5;
    network *Setnetwork;
    QLabel *label_6;
    QLabel *background;
    QLabel *label_7;
    logincircling *widget_2;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(371, 555);
        MainWindow->setAutoFillBackground(false);
        MainWindow->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        MainWindow->setWindowFlags(Qt::Window | Qt::FramelessWindowHint);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        centralWidget->setStyleSheet(QStringLiteral("QWidget{bcakground-color: rgb(85, 170, 255);}"));
        autologin = new QCheckBox(centralWidget);
        autologin->setObjectName(QStringLiteral("autologin"));
        autologin->setGeometry(QRect(30, 467, 91, 31));
        autologin->setCursor(QCursor(Qt::PointingHandCursor));
        autologin->setStyleSheet(QStringLiteral("QCheckBox {background-color: rgb(255, 255, 255); color: rgb(159, 159, 159); } QCheckBox:hover { background-color: rgb(255, 255, 255); color: rgb(85, 85, 255); }"));
        autologin->setChecked(false);
        autologin->setAutoRepeat(false);
        autologin->setTristate(false);
        newuser = new QPushButton(centralWidget);
        newuser->setObjectName(QStringLiteral("newuser"));
        newuser->setGeometry(QRect(259, 468, 81, 28));
        newuser->setCursor(QCursor(Qt::PointingHandCursor));
        newuser->setStyleSheet(QStringLiteral("QPushButton {border: 1px solid rgba(0,0,0,0); background-color: rgb(255, 255, 255); color: rgb(159, 159, 159); } QPushButton:hover { background-color: rgb(255, 255, 255); color: rgb(85, 85, 255); }"));
        newuser->setFlat(true);
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(2, 80, 368, 479));
        QFont font;
        font.setFamily(QStringLiteral("Adobe Myungjo Std M"));
        font.setPointSize(12);
        tabWidget->setFont(font);
        tabWidget->setLayoutDirection(Qt::LeftToRight);
        tabWidget->setStyleSheet(QLatin1String("QTabBar::tab:selected{margin-left: 0px; margin-right: 0;color: rgb(165, 165, 165); background-color: white;}\n"
"QTabBar::tab:!selected{margin-left: 0px; margin-right: 0;color: rgb(165, 165, 165); background-color: white;} QTabBar::tab:hover:!selected{background-color: white; color: rgb(85, 85, 255); margin-left: 0; margin-right: 0;} "));
        tabWidget->setElideMode(Qt::ElideNone);
        tabWidget->setUsesScrollButtons(false);
        tabWidget->setDocumentMode(false);
        tabWidget->setTabsClosable(false);
        tabWidget->setMovable(false);
        tabWidget->setTabBarAutoHide(false);
        Codelogin = new QWidget();
        Codelogin->setObjectName(QStringLiteral("Codelogin"));
        line_8 = new QFrame(Codelogin);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(180, 6, 158, 4));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(245, 245, 245, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(250, 250, 250, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(122, 122, 122, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(163, 163, 163, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush6(QColor(255, 255, 220, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        line_8->setPalette(palette);
        line_8->setStyleSheet(QStringLiteral("background-color: rgb(245, 245, 245)"));
        line_8->setLineWidth(2);
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(Codelogin);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(30, 6, 151, 2));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush7(QColor(85, 170, 255, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush7);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        line_4->setPalette(palette1);
        line_4->setStyleSheet(QStringLiteral("background-color: rgb(85, 170, 255)"));
        line_4->setLineWidth(2);
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        label = new QLabel(Codelogin);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(54, 283, 261, 41));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Adobe \351\273\221\344\275\223 Std R"));
        font1.setPointSize(16);
        label->setFont(font1);
        label->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(Codelogin);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(82, 50, 201, 201));
        label_2->setCursor(QCursor(Qt::ArrowCursor));
        label_2->setPixmap(QPixmap(QString::fromUtf8(":/QRcode.PNG")));
        label_2->setAlignment(Qt::AlignCenter);
        alinum_2 = new QPushButton(Codelogin);
        alinum_2->setObjectName(QStringLiteral("alinum_2"));
        alinum_2->setGeometry(QRect(0, 396, 371, 61));
        alinum_2->setCursor(QCursor(Qt::PointingHandCursor));
        alinum_2->setMouseTracking(true);
        alinum_2->setAutoFillBackground(false);
        alinum_2->setStyleSheet(QStringLiteral("QPushButton {border: 1px solid rgba(0,0,0,0); background-color: rgb(247, 247, 247); color: rgb(159, 159, 159);} QPushButton:hover {background-color: rgb(247, 247, 247); color: rgb(85, 85, 255);}"));
        alinum_2->setFlat(false);
        widget = new RefreshCicle(Codelogin);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(158, 125, 45, 45));
        tabWidget->addTab(Codelogin, QString());
        Passlogin = new QWidget();
        Passlogin->setObjectName(QStringLiteral("Passlogin"));
        logo = new QLabel(Passlogin);
        logo->setObjectName(QStringLiteral("logo"));
        logo->setGeometry(QRect(114, 50, 131, 131));
        logo->setTextFormat(Qt::AutoText);
        logo->setPixmap(QPixmap(QString::fromUtf8(":/ddlogo.PNG")));
        logo->setAlignment(Qt::AlignCenter);
        ddnum = new QLineEdit(Passlogin);
        ddnum->setObjectName(QStringLiteral("ddnum"));
        ddnum->setGeometry(QRect(130, 220, 210, 41));
        QFont font2;
        font2.setFamily(QStringLiteral("Arial"));
        font2.setPointSize(13);
        ddnum->setFont(font2);
        ddnum->setLayoutDirection(Qt::LeftToRight);
        ddnum->setStyleSheet(QStringLiteral("QLineEdit{border-with: 0; border-style: outset}"));
        ddnum->setDragEnabled(false);
        QRegExp regx("[0-9]+$");
        QValidator* validator = new QRegExpValidator(regx, ddnum);
        ddnum->setValidator(validator);
        line_2 = new QFrame(Passlogin);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(110, 230, 20, 23));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(Passlogin);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(30, 260, 311, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        ddpass = new QLineEdit(Passlogin);
        ddpass->setObjectName(QStringLiteral("ddpass"));
        ddpass->setGeometry(QRect(30, 270, 311, 41));
        ddpass->setFont(font2);
        ddpass->setStyleSheet(QStringLiteral("QLineEdit{border-with: 0; border-style: outset}"));
        ddpass->setEchoMode(QLineEdit::Password);
        login = new QCommandLinkButton(Passlogin);
        login->setObjectName(QStringLiteral("login"));
        login->setGeometry(QRect(300, 270, 31, 41));
        login->setStyleSheet(QStringLiteral("QCommandLinkButton {border: 1px solid rgba(0,0,0,0); background-color: rgb(255, 255, 255); color: rgb(85, 85, 255); } QCommandLinkButton:hover { background-color: rgb(255, 255, 255); color: rgb(85, 85, 255); }"));
        login->setAutoDefault(true);
        login->setDefault(false);
        line_6 = new QFrame(Passlogin);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(30, 305, 311, 20));
        line_6->setStyleSheet(QStringLiteral("color: rgb(250, 250, 250)"));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        forgetpass = new QPushButton(Passlogin);
        forgetpass->setObjectName(QStringLiteral("forgetpass"));
        forgetpass->setGeometry(QRect(184, 366, 71, 28));
        forgetpass->setCursor(QCursor(Qt::PointingHandCursor));
        forgetpass->setStyleSheet(QStringLiteral("QPushButton {border: 1px solid rgba(0,0,0,0); background-color: rgb(255, 255, 255); color: rgb(159, 159, 159); } QPushButton:hover { background-color: rgb(255, 255, 255); color: rgb(85, 85, 255); }"));
        forgetpass->setFlat(true);
        line = new QFrame(Passlogin);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(254, 370, 3, 20));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(Passlogin);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(180, 6, 158, 2));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        line_3->setPalette(palette2);
        line_3->setStyleSheet(QStringLiteral("background-color: rgb(85, 170, 255)"));
        line_3->setLineWidth(2);
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(Passlogin);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(30, 6, 151, 4));
        QPalette palette3;
        QBrush brush8(QColor(240, 240, 240, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush8);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush8);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        line_7->setPalette(palette3);
        line_7->setStyleSheet(QStringLiteral("color: rgb(240, 240, 240)"));
        line_7->setLineWidth(2);
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        areanum = new QPushButton(Passlogin);
        areanum->setObjectName(QStringLiteral("areanum"));
        areanum->setGeometry(QRect(30, 220, 81, 41));
        areanum->setFont(font2);
        areanum->setCursor(QCursor(Qt::PointingHandCursor));
        areanum->setContextMenuPolicy(Qt::ActionsContextMenu);
        areanum->setStyleSheet(QStringLiteral("QPushButton {text-align:left; border: 1px solid rgba(0,0,0,0);} QPushButton::menu-indicator {subcontrol-position: right center; subcontrol-origin: padding}"));
        areanum->setFlat(true);
        alinum = new QPushButton(Passlogin);
        alinum->setObjectName(QStringLiteral("alinum"));
        alinum->setGeometry(QRect(0, 396, 371, 61));
        alinum->setCursor(QCursor(Qt::PointingHandCursor));
        alinum->setMouseTracking(true);
        alinum->setAutoFillBackground(false);
        alinum->setStyleSheet(QStringLiteral("QPushButton {border: 1px solid rgba(0,0,0,0); background-color: rgb(247, 247, 247); color: rgb(159, 159, 159);} QPushButton:hover {background-color: rgb(247, 247, 247); color: rgb(85, 85, 255);}"));
        alinum->setFlat(false);
        tabWidget->addTab(Passlogin, QString());
        logo->raise();
        ddnum->raise();
        line_5->raise();
        ddpass->raise();
        login->raise();
        line_6->raise();
        forgetpass->raise();
        line->raise();
        line_3->raise();
        line_7->raise();
        areanum->raise();
        alinum->raise();
        line_2->raise();
        ForgetPass = new Forgetpass(centralWidget);
        ForgetPass->setObjectName(QStringLiteral("ForgetPass"));
        ForgetPass->setGeometry(QRect(2, 51, 367, 501));
        NewUser = new Newuser(centralWidget);
        NewUser->setObjectName(QStringLiteral("NewUser"));
        NewUser->setGeometry(QRect(2, 51, 367, 501));
        AliNum = new Alinum(centralWidget);
        AliNum->setObjectName(QStringLiteral("AliNum"));
        AliNum->setGeometry(QRect(2, 51, 367, 501));
        back = new QPushButton(MainWindow);
        back->setObjectName(QStringLiteral("back"));
        back->setGeometry(QRect(10, 2, 31, 49));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Adobe \351\273\221\344\275\223 Std R"));
        font3.setBold(true);
        font3.setWeight(75);
        back->setFont(font3);
        back->setCursor(QCursor(Qt::PointingHandCursor));
        back->setAutoFillBackground(false);
        back->setStyleSheet(QStringLiteral("QPushButton {border: 1px solid rgba(0,0,0,0); background-color: rgb(85, 170, 255); color: rgb(243, 243, 243); } QPushButton:hover { color: rgb(255, 255, 255); }"));
        back->setFlat(false);
        label_4 = new QLabel(MainWindow);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(32, 2, 61, 49));
        QPalette palette4;
        QBrush brush9(QColor(243, 243, 243, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        QBrush brush10(QColor(127, 127, 127, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush10);
        QBrush brush11(QColor(170, 170, 170, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush11);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush9);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush7);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush10);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        label_4->setPalette(palette4);
        QFont font4;
        font4.setFamily(QString::fromUtf8("\351\273\221\344\275\223"));
        font4.setPointSize(14);
        label_4->setFont(font4);
        label_4->setStyleSheet(QStringLiteral(" background-color: rgb(85, 170, 255); color: rgb(243, 243, 243);"));
        label_4->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(MainWindow);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(2, 2, 91, 49));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush10);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush11);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush9);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush10);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush11);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        label_3->setPalette(palette5);
        label_3->setFont(font4);
        label_3->setStyleSheet(QStringLiteral(" background-color: rgb(85, 170, 255); color: rgb(243, 243, 243);"));
        label_3->setAlignment(Qt::AlignCenter);
        titlebar = new titlebar1(MainWindow);
        titlebar->setObjectName(QStringLiteral("titlebar"));
        titlebar->setGeometry(QRect(2, 2, 367, 51));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush7);
        QBrush brush12(QColor(213, 234, 255, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush12);
        QBrush brush13(QColor(149, 202, 255, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush13);
        QBrush brush14(QColor(42, 85, 127, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush14);
        QBrush brush15(QColor(56, 113, 170, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush15);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush7);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush16(QColor(170, 212, 255, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush16);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush12);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush13);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush14);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush15);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush16);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush14);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush13);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush14);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush15);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush14);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush14);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        titlebar->setPalette(palette6);
        titlebar->setAutoFillBackground(false);
        titlebar->setStyleSheet(QStringLiteral("background-color: rgb(85, 170, 255)"));
        setNetwork = new QPushButton(MainWindow);
        setNetwork->setObjectName(QStringLiteral("setNetwork"));
        setNetwork->setGeometry(QRect(268, 12, 31, 27));
        setNetwork->setFont(font);
        setNetwork->setCursor(QCursor(Qt::PointingHandCursor));
        setNetwork->setStyleSheet(QStringLiteral("QPushButton {border: 1px solid rgba(0,0,0,0); background-color: rgb(85, 170, 255); color: rgb(243, 243, 243); } QPushButton:hover { color: rgb(255, 255, 255); }"));
        setNetwork->setFlat(true);
        label_5 = new QLabel(MainWindow);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(32, 2, 111, 49));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush10);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush11);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush9);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush7);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush10);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush11);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        label_5->setPalette(palette7);
        label_5->setFont(font4);
        label_5->setStyleSheet(QStringLiteral("background-color: rgb(85, 170, 255); color: rgb(243, 243, 243);"));
        label_5->setAlignment(Qt::AlignCenter);
        Setnetwork = new network(centralWidget);
        Setnetwork->setObjectName(QStringLiteral("Setnetwork"));
        Setnetwork->setGeometry(QRect(2, 51, 367, 585));
        Setnetwork->setStyleSheet(QStringLiteral(""));
        label_6 = new QLabel(MainWindow);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(35, 72, 308, 45));
        label_6->setPixmap(QPixmap(QString::fromUtf8(":/warningNumPass.PNG")));
        background = new QLabel(centralWidget);
        background->setObjectName(QStringLiteral("background"));
        background->setGeometry(QRect(0, 0, 371, 560));
        QPalette palette8;
        QBrush brush17(QColor(236, 236, 236, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush17);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush17);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush17);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush17);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush17);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush17);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush17);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush17);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush17);
        background->setPalette(palette8);
        background->setAutoFillBackground(false);
        background->setStyleSheet(QStringLiteral("QLabel{background-color: rgb(236, 236, 236);}"));
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(2, 53, 367, 50));
        widget_2 = new logincircling(centralWidget);
        widget_2->setObjectName(QStringLiteral("widget_2"));
        widget_2->setGeometry(QRect(2, 51, 367, 501));
        MainWindow->setCentralWidget(centralWidget);
        background->raise();
        label_7->raise();
        titlebar->raise();
        AliNum->raise();
        ForgetPass->raise();
        NewUser->raise();
        back->raise();
        label_5->raise();
        label_4->raise();
        label_3->raise();
        Setnetwork->raise();
        label_6->raise();
        setNetwork->raise();
        widget_2->raise();
        tabWidget->raise();
        autologin->raise();
        newuser->raise();

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "\351\222\211\351\222\211", Q_NULLPTR));
        autologin->setText(QApplication::translate("MainWindow", "\350\207\252\345\212\250\347\231\273\345\275\225", Q_NULLPTR));
        newuser->setText(QApplication::translate("MainWindow", "\346\226\260\347\224\250\346\210\267\346\263\250\345\206\214", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "\346\211\213\346\234\272\351\222\211\351\222\211\346\211\253\347\240\201\347\231\273\351\231\206", Q_NULLPTR));
        label_2->setText(QString());
        alinum_2->setText(QApplication::translate("MainWindow", "\351\230\277\351\207\214\345\233\275\351\231\205\347\253\231\345\270\220\345\217\267\347\231\273\345\275\225", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(Codelogin), QApplication::translate("MainWindow", "          \346\211\253\347\240\201\347\231\273\345\275\225     ", Q_NULLPTR));
        logo->setText(QString());
        ddnum->setText(QString());
        ddnum->setPlaceholderText(QApplication::translate("MainWindow", "\350\257\267\350\276\223\345\205\245\346\211\213\346\234\272\345\217\267", Q_NULLPTR));
        ddpass->setPlaceholderText(QApplication::translate("MainWindow", "\350\257\267\350\276\223\345\205\245\345\257\206\347\240\201", Q_NULLPTR));
        login->setText(QString());
        forgetpass->setText(QApplication::translate("MainWindow", "\345\277\230\350\256\260\345\257\206\347\240\201", Q_NULLPTR));
        areanum->setText(QApplication::translate("MainWindow", "+86        ", Q_NULLPTR));
        alinum->setText(QApplication::translate("MainWindow", "\351\230\277\351\207\214\345\233\275\351\231\205\347\253\231\345\270\220\345\217\267\347\231\273\345\275\225", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(Passlogin), QApplication::translate("MainWindow", "     \345\257\206\347\240\201\347\231\273\345\275\225         ", Q_NULLPTR));
        back->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "\351\222\211\351\222\211", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "\351\222\211\351\222\211", Q_NULLPTR));
        setNetwork->setText(QApplication::translate("MainWindow", "\357\271\200", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "\347\275\221\347\273\234\350\256\276\347\275\256", Q_NULLPTR));
        label_6->setText(QString());
        background->setText(QString());
        label_7->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
